
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:805945173734:android:14a8ece24eedd76b773d27",
        firebase_cli_token: "1//03wFcDc7mfr6ACgYIARAAGAMSNwF-L9IraOJR-rNK34P05lCQMsmhDgZusKrfzaqE-Sga05eT995_RS4YT0MyqYr0z5OI97J4L6g",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "hashimsaffarini2004@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end